package com.hust.edu.vn.documentsystem.common.type;

public enum NotificationType {
    NEW_DOCUMENT, DELETE_DOCUMENT, EDIT_DOCUMENT,
    NEW_SUBJECT_DOCUMENT, EDIT_SUBJECT_DOCUMENT, DELETE_SUBJECT_DOCUMENT,
    NEW_COMMENT_POST, DELETE_COMMENT_POST, EDIT_COMMENT_POST,
    NEW_COMMENT_SUBJECT_DOCUMENT, EDIT_COMMENT_SUBJECT_DOCUMENT, DELETE_COMMENT_SUBJECT_DOCUMENT,
    NEW_COMMENT_REVIEW_TEACHER, EDIT_COMMENT_REVIEW_TEACHER, DELETE_COMMENT_REVIEW_TEACHER,
    NEW_COMMENT_REVIEW_SUBJECT, EDIT_COMMENT_REVIEW_SUBJECT, DELETE_COMMENT_REVIEW_SUBJECT,
    NEW_ANSWER, DELETE_ANSWER, EDIT_ANSWER,
    NEW_REPORT, DELETE_REPORT, EDIT_REPORT,
    NEW_POST, DELETE_POST, EDIT_POST,
    NEW_REVIEW_TEACHER, DELETE_REVIEW_TEACHER, EDIT_REVIEW_TEACHER,
    NEW_REVIEW_SUBJECT, DELETE_REVIEW_SUBJECT, EDIT_REVIEW_SUBJECT,
    NEW_USER, EDIT_USER, DELETE_USER,
    TRANSLATED,
    HIDDEN_COMMENT_PORT, ACTIVE_COMMENT_PORT,
    HIDDEN_ANSWER_PORT, ACTIVE_ANSWER_PORT,
    HIDDEN_PORT, ACTIVE_PORT,
    HIDDEN_COMMENT_SUBJECT_DOCUMENT, ACTIVE_COMMENT_SUBJECT_DOCUMENT,
    SHARE_DOCUMENT_PRIVATE,
    HIDDEN_COMMENT_REVIEW_TEACHER, ACTIVE_COMMENT_REVIEW_TEACHER,
    HIDDEN_REVIEW_TEACHER, ACTIVE_REVIEW_TEACHER,
    ALL;
}
