package com.hust.edu.vn.documentsystem.common.type;

public enum SocketMessageType {
    NEW_COMMENT, NEW_POST, NEW_REPORT, NEW_DOCUMENT, NEW_REVIEW, NEW_USER,
    EDIT_REVIEW, EDIT_COMMENT, EDIT_POST, EDIT_REPORT, EDIT_DOCUMENT,
    DELETE_COMMENT, DELETE_POST, DELETE_REPORT, DELETE_DOCUMENT, DELETE_USER

}
