server:
  port: ${PORT}
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql:${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      data-source-properties:
        socketFactory: com.google.cloud.sql.postgres.SocketFactory
        cloudSqlInstance: ${CLOUD_SQL_INSTANCE}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
  mail:
    host: smtp.office365.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.office365.com
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  cloud:
    gcp:
      vision:
        enabled: true
      sql:
        database-name: ${DB_NAME}
        instance-connection-name: ${CLOUD_SQL_INSTANCE}



