server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql:hust-document
    username: hust-document-system-db
    password: Cuong123@123
    hikari:
      data-source-properties:
        socketFactory: com.google.cloud.sql.postgres.SocketFactory
        cloudSqlInstance: hust-doument-system:asia-south1:hust-document-system-db
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
  mail:
    host: smtp.office365.com
    port: 587
    username: cuong.nnc184055@sis.hust.edu.vn
    password: ldjQKW57
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.office365.com
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  cloud:
    gcp:
      vision:
        enabled: true
      sql:
        database-name: hust-document
        instance-connection-name: hust-doument-system:asia-south1:hust-document-system-db
